
# https://stackoverflow.com/questions/74019073/how-to-get-nested-data-with-pandas-and-request#comment130693011_74019073


api_response = {
  "ConfirmFlag": False,
  "ConfirmValue": None,
  "ConfirmValueData": None,
  "Data": [
    {
      "SoEstimateHeader": {
        "AllocatableAmount": 0,
        "AllocationPercentage": 0,
        "AllocationPercentagePreview": 0,
        "AllocationStatusId": None,
        "AllocationStatusName": None,
        "ApplyPricingRule": False,
        "ApprovalStatusChangeDttm": None,
        "ApprovalStatusChangeSource": None,
        "ApprovalStatusName": None,
        "AuthorizationDetailList": None,
        "AutoCreateCarrierFlag": False,
        "AutoDepositTotalAmount": None,
        "BillToAddr": "1312 Seymour Cir",
        "BillToAddr2": "",
        "BillToAddrName": None,
        "BillToCity": "Lincoln",
        "BillToCompanyName": "",
        "BillToCountry": "USA",
        "BillToCountryISO2": None,
        "BillToEmail": "",
        "BillToFirstName": "",
        "BillToLastName": "",
        "BillToName": "",
        "BillToPhoneNumber": "",
        "BillToState": "CA",
        "BillToStateAbbr": None,
        "BillToZpCode": "95648",
        "BrandId": None,
        "BrandName": None,
        "BuyerId": None,
        "BuyerName": None,
        "CampaignId": None,
        "CampaignName": None,
        "CancelledFlag": False,
        "CaptureLater": False,
        "CardId": None,
        "cardLast4Digits": None,
        "CardNumber": None,
        "CardPaymentProcessedFlag": False,
        "CarrierId": 1321,
        "CarrierName": "UPS",
        "ChargeId": None,
        "ChargeTypeId": None,
        "CreateDttm": "03/03/2020 10:31:22 PM",
        "CreateSource": "xtest10012",
        "CurrencyCode": "USD",
        "CurrencyId": 1001,
        "CurrencyName": "United States Dollar",
        "CurrencySymbol": "$         ",
        "CustomerContact": "",
        "CustomerDefaultBillingEmail": None,
        "CustomerDefaultShipmentupdatesEmail": None,
        "CustomerEmailCC": None,
        "CustomerEmailMain": "",
        "CustomerFirstName": None,
        "CustomerFullName": "Customer 1",
        "CustomerGroupId": 9,
        "CustomerId": 6113,
        "CustomerLastName": None,
        "CustomerMainPhone": "",
        "CustomerMessage": "",
        "CustomerName": "Customer 1",
        "CustomerPO": "123456",
        "CustomerServiceRepFullName": None,
        "CustomerServiceRepId": None,
        "CustomerTaxCodeId": None,
        "CustomFieldH1": None,
        "CustomFieldH10": None,
        "CustomFieldH11": None,
        "CustomFieldH12": None,
        "CustomFieldH13": None,
        "CustomFieldH14": None,
        "CustomFieldH15": None,
        "CustomFieldH16": None,
        "CustomFieldH17": None,
        "CustomFieldH18": None,
        "CustomFieldH19": None,
        "CustomFieldH2": None,
        "CustomFieldH20": None,
        "CustomFieldH21": None,
        "CustomFieldH22": None,
        "CustomFieldH23": None,
        "CustomFieldH24": None,
        "CustomFieldH25": None,
        "CustomFieldH26": None,
        "CustomFieldH27": None,
        "CustomFieldH28": None,
        "CustomFieldH29": None,
        "CustomFieldH3": None,
        "CustomFieldH30": None,
        "CustomFieldH4": None,
        "CustomFieldH5": None,
        "CustomFieldH6": None,
        "CustomFieldH7": None,
        "CustomFieldH8": None,
        "CustomFieldH9": None,
        "Cvc": None,
        "DateFirstShip": None,
        "DateFulFilled": None,
        "DateLastShip": None,
        "DateRelease": None,
        "DateTimeCancelled": None,
        "DateToBeCancelled": None,
        "DateToBeShipped": "10/20/2019",
        "DefaultLocationId": None,
        "DefaultLocationName": None,
        "DepositAccountName": None,
        "DepositAmount": None,
        "DepositDue": 73.93,
        "DepositEmailSentCount": 0,
        "DepositEmailSentFlag": False,
        "DepositRequiredAmount": 20,
        "DepositRequiredFlag": True,
        "DepositRequiredType": 20,
        "DepositRequiredTypeName": None,
        "DiscountAmount": 0,
        "Email": None,
        "EstimateFollowUpDate": None,
        "EstimateToSoFlag": False,
        "EstimateValidUntilDate": None,
        "ExchangeRate": 1,
        "ExchangeRateFormula": None,
        "ExpirationMonth": None,
        "ExpirationYear": None,
        "FobId": 20,
        "FobName": "Destination",
        "FullfillmentPercentage": 0,
        "HasRestrictionFlag": False,
        "Id": 23897,
        "ImageList": None,
        "IntAccntId": None,
        "InvoiceCounter": 0,
        "IsClosed": False,
        "IsCreatedFromB2BFlag": False,
        "IsEstimateModule": False,
        "IsOrderTaxExempt": False,
        "IsTaxableFlag": 0,
        "LastDateToBeShipped": None,
        "LastDepositEmailSentDttm": None,
        "LastDepositEmailSentSource": "",
        "LiabilityAccountName": None,
        "Memo": "This is a memo",
        "MerchantResponseData": None,
        "MerchantReturnRefNumber": None,
        "MerchantTypeId": None,
        "MetaData": None,
        "ModifyDttm": "03/22/2020 09:58:09 PM",
        "ModifySource": "kunalx",
        "NameOnCard": None,
        "NoTaxCompareFlag": False,
        "OrderClassCode": "ON",
        "OrderClassName": "Online",
        "OrderDate": "10/03/2018",
        "OrderNumber": "MAIN-S003607",
        "OrderRefNumber": None,
        "OrderTypeCode": None,
        "OrderTypeName": None,
        "PaymentAmount": 0,
        "PaymentCurrencyId": 0,
        "PaymentMethodName": None,
        "PaymentProcessed": False,
        "PaymentReceipt": None,
        "PaymentServiceAccountId": 0,
        "PaymentTermsId": 10,
        "PaymentTermsName": "COD",
        "PresentationCode": None,
        "PresentationId": 0,
        "PresentationName": None,
        "PriorityId": None,
        "PriorityName": "",
        "ProcessCreditCard": False,
        "ProjectClassId": 1,
        "ProjectClassName": "Online",
        "QtyToAllocateAfter": 0,
        "QtyToAllocateBefore": 0,
        "ReCalcShippingTaxesFlag": False,
        "ReCalcTaxesFlag": False,
        "RecalculateTaxes": False,
        "RefId": None,
        "RefNo": "RefNo203892-1",
        "ReportDataObj": {
          "EntityAccntId": "C7A82F0E-53F2-4934-875F-BBA04F907FCB",
          "EntityName": "Customer 1",
          "ReportEntityId": 103,
          "TxnRefId": 23897,
          "TxnRefNumber": "MAIN-S003607",
          "TxnTypeId": 116
        },
        "ResidentialFlag": None,
        "RiskAnalysis": None,
        "SalesRepFullName": "Derek Brad",
        "SalesRepId": "dbrad",
        "SaleStoreId": 10002,
        "SaleStoreName": "Main Warehouse",
        "SaveCreditCardInfo": False,
        "ShipMethodId": 30,
        "ShipMethodName": "Delivery (Third Party)",
        "ShipPackageTypeId": None,
        "ShippingAccountNumber": "",
        "ShippingAmount": 107.25,
        "ShippingCost": 100,
        "ShippingCostInvoiced": None,
        "ShippingCostRemaining": 100,
        "ShippingNotes": "This is Shipping Notes",
        "ShippingTaxCodeId": 1000,
        "ShippingTaxCodeName": "CA TAX 7.25%",
        "ShippingTaxData": {
          "taxItems": [
            {
              "itemAmount": 7.25,
              "itemId": 1000,
              "itemName": "CA TAX 7.25%",
              "itemRatePerc": 7.25,
              "lineAmount": 100
            }
          ],
          "totalAmount": 7.25
        },
        "ShippingTaxItems": [
          {
            "Id": 1000,
            "Name": "CA TAX 7.25%",
            "Rate": 0.0725,
            "RateType": "percentage",
            "TotalAmount": 7.25
          }
        ],
        "ShippingTermsId": 30,
        "ShippingTermsName": "Prepaid & Billed",
        "ShippingTypeId": None,
        "ShippingTypeName": "",
        "ShipServiceCode": "UPSG",
        "ShipServiceId": 58,
        "ShipServiceName": "UPS Ground",
        "ShipToAddr": "1312 Seymour Cir",
        "ShipToAddr2": "",
        "ShipToAddrName": "",
        "ShipToCity": "Lincoln",
        "ShipToCompanyName": "",
        "ShipToCountry": "USA",
        "ShipToCountryISO2": None,
        "ShipToEmail": "",
        "ShipToFirstName": "",
        "ShipToLastName": "",
        "ShipToName": "",
        "ShipToPhoneNumber": "",
        "ShipToState": "CA",
        "ShipToStateAbbr": None,
        "ShipToZpCode": "95648",
        "SoSubTypeId": 1,
        "SoSubTypeName": "SS18 D3",
        "StatusId": 10,
        "StatusName": "Open",
        "StoreId": 10002,
        "StoreName": "Main Warehouse",
        "SubTotal": 0,
        "SubTotalExclDiscount": 0,
        "Tags": "TagX,TagY",
        "TaxCalcByAddress": False,
        "TaxCalcType": None,
        "TaxOperationCountryCode": None,
        "TaxSummaryDataText": None,
        "TemplateId": None,
        "ThirdPartyDefaultSKU": None,
        "ThirdPartyDisplayName": " Shopify",
        "ThirdPartyFulfillmentAccount": None,
        "ThirdPartyFulfillmentRefId": None,
        "ThirdPartyFulfillmentStatus": None,
        "ThirdPartyIconUrl": "https://image-url-for-source",
        "ThirdPartyRefNo": "Order123",
        "ThirdPartyShippingRefNo": "",
        "ThirdPartySource": "Shopify-Account1",
        "ThirdPartyTotalAmount": None,
        "ThirdPartyTotalTaxAmount": 0,
        "ToBeEmailedFlag": None,
        "ToBeMailedFlag": None,
        "ToBePrintedFlag": None,
        "TotalAmount": 519.63,
        "TotalDeposit": 30,
        "TotalQty": 0,
        "TotalTaxAmount": 35.13,
        "TotalWaveCount": 0,
        "TotalWeight": None,
        "TrackingNumbers": None,
        "TransactionComplete": False,
        "TransferFromStoreId": None,
        "TransferFromStoreName": None,
        "TransferPoId": None,
        "TransferPoNumber": "",
        "TransferProcessedFlag": False,
        "TransferToStoreId": None,
        "TransferToStoreName": "",
        "TxnId": None,
        "TxnNumber": 0,
        "TxnTypeId": None,
        "TypeId": 20,
        "TypeName": "Sale",
        "UpdateExchangeRateFlag": False,
        "UseDefaultSKUWhenError": False,
        "UseDifferentPaymentServiceAccount": False,
        "VendorPO": "",
        "WeightUomId": 2
      },
      "SoEstimateItemLineArr": [
        {
          "AmountAllocatedBefore": 0,
          "AmountAllocatedPreview": 0,
          "AuthorizationDetailList": None,
          "AutoVoidWaveLine": False,
          "BasePartNumber": "BC",
          "BaseUomId": 4,
          "BaseUomName": "Each",
          "CloseFlag": None,
          "CreateDttm": "03/03/2020 10:31:22 PM",
          "CreateSource": None,
          "CurrencySymbol": None,
          "CustomFieldD1": "",
          "CustomFieldD10": "",
          "CustomFieldD11": "",
          "CustomFieldD12": "",
          "CustomFieldD13": "",
          "CustomFieldD14": "",
          "CustomFieldD15": "",
          "CustomFieldD16": "",
          "CustomFieldD17": "",
          "CustomFieldD18": "",
          "CustomFieldD19": "",
          "CustomFieldD2": "",
          "CustomFieldD20": "",
          "CustomFieldD21": "",
          "CustomFieldD22": "",
          "CustomFieldD23": "",
          "CustomFieldD24": "",
          "CustomFieldD25": "",
          "CustomFieldD26": "",
          "CustomFieldD27": "",
          "CustomFieldD28": "",
          "CustomFieldD29": "",
          "CustomFieldD3": "",
          "CustomFieldD30": "",
          "CustomFieldD4": "",
          "CustomFieldD5": "",
          "CustomFieldD6": "",
          "CustomFieldD7": "",
          "CustomFieldD8": "",
          "CustomFieldD9": "",
          "DateFirstShip": None,
          "DateFulfilled": None,
          "DateLastShip": None,
          "DateRelease": None,
          "DateToBeShipped": "10/20/2019",
          "DefaultVendorId": None,
          "DefaultVendorName": "",
          "DeleteFlag": False,
          "Description": "Battery Connector",
          "Discount": 50,
          "DiscountTypeId": 10,
          "DiscountTypeName": "percentage",
          "EditState": True,
          "EffectiveUnitPrice": 384.5,
          "ExternalItemNumber": "",
          "ForceSalesTaxCode": False,
          "HasRestriction": False,
          "Id": 40668,
          "ImageList": None,
          "ImagePath": "",
          "IsKitHeader": False,
          "IsKitItem": False,
          "IsoCode2": "",
          "IsoCountryName": "",
          "IsTaxableFlag": True,
          "ItemId": 30111,
          "ItemNotes": None,
          "ItemNumber": "BC",
          "ItemTypeId": 10,
          "ItemTypeName": "Inventory",
          "ItemUpc": "",
          "KitItemFactor": 1,
          "LastDateToBeShipped": None,
          "LineNumber": 1,
          "MasterKitId": None,
          "MasterKitKey": "",
          "MetaData": "",
          "ModifyDttm": None,
          "ModifySource": None,
          "MoRefNumbers": "",
          "Notes": "Test notes",
          "OpenFLag": None,
          "Option1Name": "",
          "Option1Value": "",
          "Option1ValueCode": "",
          "Option2Name": "",
          "Option2Value": "",
          "Option2ValueCode": "",
          "ProductHeaderId": 4669,
          "ProjectClassId": None,
          "ProjectClassName": "",
          "Qty": 1,
          "QtyAllocated": 0,
          "QtyAllocatedPreview": None,
          "QtyDecimalFlag": False,
          "QtyOrdered": 1,
          "QtyRemainingToShip": 1,
          "QtyShipped": 0,
          "RefId": None,
          "RestrictionOverrideFlag": False,
          "RestrictionOverridePrice": None,
          "RestrictionOverrideUser": "",
          "SellUomId": 4,
          "SellUomName": "Each",
          "SoId": 23897,
          "StatusId": 10,
          "StatusName": "Open",
          "TaxAmount": 27.8763,
          "TaxCodeId": 1000,
          "TaxCodeName": "CA TAX 7.25%",
          "TaxData": {
            "taxItems": [
              {
                "itemAmount": 27.8763,
                "itemId": 1000,
                "itemName": "CA TAX 7.25%",
                "itemRatePerc": 7.25,
                "lineAmount": 384.5
              }
            ],
            "totalAmount": 27.8763
          },
          "TaxItems": [
            {
              "Id": 1000,
              "Name": "CA TAX 7.25%",
              "Rate": 0.0725,
              "RateType": "percentage",
              "TotalAmount": 27.8763
            }
          ],
          "ThirdPartyRefNo": "",
          "ThirdPartySourceHeader": None,
          "TotalAmount": 384.5,
          "TxnTypeId": None,
          "UnitPrice": 769,
          "UomFactor": None,
          "VariantInfo": "",
          "VariantInfoColored": "",
          "VASItemCost": None,
          "VASItemId": None,
          "VASItemName": "",
          "WaveLineId": 0,
          "Weight": None,
          "WeightUomId": 2
        }
      ]
    }
  ],
  "EndRequest": True,
  "ErrorCode": 0,
  "IsForwardRequest": False,
  "LogFlag": True,
  "Message": "Order data loaded successfully",
  "MessageTitle": None,
  "MetaData": "",
  "Result": True
}

data_list = api_response['Data']

#the data_list is only one element long, so grab the first element which is a dictionary

data = data_list[0]

so_estimate_header = data['SoEstimateHeader']

# similar to the data list this "SoEstimateItemLineArr" is of type list and has 1 element in
so_estimate_item_line_arr = data['SoEstimateItemLineArr'][0]

qtyremainingtoship = so_estimate_item_line_arr["QtyRemainingToShip"]
itemnumber = so_estimate_item_line_arr["ItemNumber"]

print("QtyRemainingToShip: ", qtyremainingtoship)
print("ItemNumber: ", itemnumber)
